language: java

jdk:
  - oraclejdk11
  
services:
  - mongodb
  - redis
  - postgresql
 
script:
  - ./mvnw clean verify
cache:
  directories:
    - '$HOME/.m2/repository'
    
after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
