version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres
    environment:
      POSTGRES_DB: rest
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"

volumes:
  postgres-data: